#!/usr/bin/env ruby

require 'rubygems'
require 'bundler'
Bundler.setup

$:.push File.dirname(__FILE__)
require 'init'

require 'delayed_job'
require 'delayed/command'

Delayed::Command.new(ARGV).daemonize
